query GetTransaction($user: ID, $asset: ID) {
  Transactions(user: $user, asset: $asset) {
    id
    description
    amount
    total
    createdAt
    updatedAt
    asset {
      code
      name
      description
    }
    prev {
      id
      amount
      total
      description
    }
  }
}