mutation (
  $description: String
  $amount: Int
  $asset: ID
  $type: TYPE
) {
  createTransaction(
    input: {
      description: $description
      amount: $amount
      asset: $asset
      type: $type
    }
  ) {
    id
    description
    amount
    createdAt
    updatedAt
  }
}
