mutation (
  $description: String
  $amount: Int
  $total: Int
  $user: ID
  $asset: ID
  $prev: ID
) {
  createTransaction(
    input: {
      description: $description
      amount: $amount
      total: $total
      user: $user
      asset: $asset
      prev: $prev
    }
  ) {
    id
    description
    total
    amount
    asset {
      id
    }
    prev {
      amount
      total
      id
    }
  }
}
